In [1]:
import pandas as pd
import mysql.connector as msc
import datetime as dt
import numpy as np
from collections import Counter

In [2]:
engine = msc.connect(user='root', password='asdfghjkl;',
                              host='127.0.0.1',
                              database='rideaustin')
# engine.close()


# Importing Unfulfilled Rides (by no_driver_available)

In [3]:
df = pd.read_sql('SELECT start_location_lat,start_location_long, created_date FROM rides  WHERE status = "NO_AVAILABLE_DRIVER";', engine)

In [4]:
#filtering the points outside of Austin
df = df[(df['start_location_lat'] >= 30.190833) & (df['start_location_lat'] <= 30.404041)]
df = df[(df['start_location_long'] >=-97.819014) & (df['start_location_long'] <= -97.647192)]

In [5]:
df['day'] = df['created_date'].dt.date

In [6]:
df_birthday = df[df['day'] == dt.date(2016,10,9)]
df_birthday.head()

start_location_lat  start_location_long        created_date         day
95844           30.268495           -97.745511 2016-10-09 00:00:03  2016-10-09
95845           30.268495           -97.745511 2016-10-09 00:00:13  2016-10-09
95846           30.268495           -97.745511 2016-10-09 00:00:54  2016-10-09
95847           30.268495           -97.745511 2016-10-09 00:02:13  2016-10-09
95848           30.275029           -97.770791 2016-10-09 00:18:38  2016-10-09

In [7]:
lats = list(df_birthday['start_location_lat'])
longs = list(df_birthday['start_location_long'])

In [8]:
from bokeh.io import output_file, show, output_notebook
from bokeh.models import (
  GMapPlot, GMapOptions, ColumnDataSource, Circle, DataRange1d, PanTool, WheelZoomTool, BoxSelectTool
)

map_options = GMapOptions(lat=30.29, lng=-97.73, map_type="roadmap", zoom=11)

plot = GMapPlot(
    x_range=DataRange1d(), y_range=DataRange1d(), map_options=map_options
)
plot.title.text = "Austin"

# For GMaps to function, Google requires you obtain and enable an API key:
#
#     https://developers.google.com/maps/documentation/javascript/get-api-key
#
# Replace the value below with your personal API key:
plot.api_key = "AIzaSyD1mSyY66mEBQLvVvdUt8vtXqS0xf6pHfI"

source = ColumnDataSource(
    data=dict(
        lat=lats,
        lon=longs,
    )
)

circle = Circle(x="lon", y="lat", size=15, fill_color="blue", fill_alpha=0.8, line_color=None)
plot.add_glyph(source, circle)

plot.add_tools(PanTool(), WheelZoomTool(), BoxSelectTool())
show(plot)

# K-Means Clustering

In [9]:
from sklearn.cluster import KMeans
X = np.array(df_birthday[['start_location_lat','start_location_long']])
model = KMeans(n_clusters=5)

In [10]:
model.fit(X)
centroids = model.cluster_centers_
centroids

array([[ 30.27492015, -97.74140333],
       [ 30.31425359, -97.71725065],
       [ 30.25818681, -97.77361078],
       [ 30.2236936 , -97.74475791],
       [ 30.37496136, -97.7536776 ]])

In [11]:
centroidlats = centroids[:,0]
centroidlongs = centroids[:,1]

In [12]:
map_options = GMapOptions(lat=30.29, lng=-97.73, map_type="roadmap", zoom=11)

plot = GMapPlot(
    x_range=DataRange1d(), y_range=DataRange1d(), map_options=map_options, api_key = "AIzaSyBx-cLXm4jxpg0aX_nnUnwd2hir3Ve0j9w")
plot.title.text = "Austin"

# For GMaps to function, Google requires you obtain and enable an API key:
#
#     https://developers.google.com/maps/documentation/javascript/get-api-key
#
# Replace the value below with your personal API key:

source = ColumnDataSource(
    data=dict(
        lat=lats,
        lon=longs,
    )
)
source1 = ColumnDataSource(
    data=dict(
        lat=centroidlats,
        lon=centroidlongs,
    )
)


circle = Circle(x="lon", y="lat", size=15, fill_color="blue", fill_alpha=0.8, line_color=None)
circle1 = Circle(x="lon", y="lat", size=45, fill_color="red", fill_alpha=0.7, line_color=None)
plot.add_glyph(source, circle)
plot.add_glyph(source1,circle1)
plot.add_tools(PanTool(), WheelZoomTool(), BoxSelectTool())
show(plot)

# Breaking it down by time block (12pm-3pm)

In [13]:
noon = df_birthday[(df_birthday['created_date'] > dt.datetime(2016,10,9, 12,0,3)) & \
                   (df_birthday['created_date'] < dt.datetime(2016,10,9, 15,0,3)) ]
noon_lats = list(noon['start_location_lat'])
noon_longs = list(noon['start_location_long'])
X= np.array(noon[['start_location_lat','start_location_long']])


In [14]:
def create_centroids(dataframe):
    ''' 
    Takes a dataframe of my start_location_lats and start_location_longs and builds a K-Means model with 5 centroids.
    It returns a numpy array of the centroids (by lat-long pair) and a dictionary where the key is the centroid rank 
    and the value is a list of the [lat,long,# of datapoints, rank] for that centroid.
    
    INPUT:
    - Dataframe
    OUTPU:
    - numpy array
    - dictionary'''
    
    X = np.array(dataframe[['start_location_lat','start_location_long']])
    model = KMeans(n_clusters=5)
    model.fit(X)
    cents = model.cluster_centers_
    lables_model = model.labels_
    c = Counter(lables_model)
    centroids_by_intensity = c.most_common(5)
    ordered_labels = [i for i,x in centroids_by_intensity]
    ordered_centroids = []
    centroid_dict = {}

    for i, index in enumerate(ordered_labels):
        ordered_centroids.append(cents[index])
        centroid_dict[i] = [cents[index][0],cents[index][1],centroids_by_intensity[i][1],i]
    
    print np.array(ordered_centroids)
    print centroid_dict
    return np.array(ordered_centroids), centroid_dict 


In [15]:
noon_ordered_centroids, noon_dict = create_centroids(noon)
length = len(noon)
print length

[[ 30.28435671 -97.74934455]
 [ 30.23832012 -97.76697088]
 [ 30.30856848 -97.78266161]
 [ 30.32807444 -97.70701346]
 [ 30.24189414 -97.72378157]]
{0: [30.284356706724896, -97.749344548876891, 58, 0], 1: [30.238320115384614, -97.76697088461539, 26, 1], 2: [30.30856847826087, -97.782661608695648, 23, 2], 3: [30.328074436363636, -97.707013459090916, 22, 3], 4: [30.241894142857142, -97.723781571428574, 7, 4]}
136


In [16]:
def plot_Austin_centroids(centroids, centroid_dictionary,num_datapoints, completed_rides=None, unfulfilled_rides=None):
    '''
    Takes in centroid values from create_centroids() and centroid_dictionary and plots the centroids relative to their
    intensity. Optional inputs for the lat-long columns for completed_rides (green) and unfulfilled_rides(blue).
    
    INPUT:
    - centroids (numpy array)
    - centroid_dict (dictionary)
    - copmleted_rides (dataframe)
    - unfulfilled_rides (dataframe)
    
    OUTPUT:
    -None
    '''
    #creating the plot
    map_options = GMapOptions(lat=30.29, lng=-97.73, map_type="roadmap", zoom=11)

    plot = GMapPlot(
        x_range=DataRange1d(), y_range=DataRange1d(), map_options=map_options
    )
    plot.title.text = "Austin"
    plot.api_key = "AIzaSyBx-cLXm4jxpg0aX_nnUnwd2hir3Ve0j9w"
    
    #create alpha based on intensity
    alpha = []
    for key, value in centroid_dictionary.iteritems():
        al_value = value[2]/float(num_datapoints)
        al_fixed = al_value+.25
        alpha.insert(key,al_fixed)
    
    #try if completed_rides is populated
    try:
        completed_lats = list(completed_rides['start_location_lat'])
        completed_longs = list(completed_rides['start_location_long'])
        completed_source = ColumnDataSource( data=dict(
            lat=completed_lats,
            lon=completed_longs,
    )
)
        completed_dots = Circle(x="lon", y="lat", size=15, fill_color="green", fill_alpha=0.1, line_color=None)
        plot.add_glyph(completed_source, completed_dots)
    except:
        pass
    
    #try if unfulfilled_rides is populated
    try:
        unfulfilled_lats = list(unfulfilled_rides['start_location_lat'])
        unfulfilled_longs = list(unfulfilled_rides['start_location_long'])
        unfulfilled_source = ColumnDataSource(
        data=dict(
            lat=unfulfilled_lats,
            lon=unfulfilled_longs,

        )
    )
        unfulfilled_dots = Circle(x="lon", y="lat", size=15, fill_color="blue", fill_alpha=0.8, line_color=None)
        plot.add_glyph(unfulfilled_source, unfulfilled_dots)
    except:
        pass
    
    #creating centroid source and circle
    centroidlats = centroids[:,0]
    centroidlongs = centroids[:,1]
    print centroidlats
    centroid_source = ColumnDataSource(
        data=dict(
            lat=centroidlats, 
            lon=centroidlongs,
             alpha=alpha
        )
    )
    print alpha
    centroid_dots = Circle(x="lon", y="lat", size=45, fill_color='#8B008B', fill_alpha='alpha', line_color=None)
    plot.add_glyph(centroid_source, centroid_dots)
    
    #finishing the plot
    plot.add_tools(PanTool(), WheelZoomTool(), BoxSelectTool())
    show(plot)

In [17]:
plot_Austin_centroids(noon_ordered_centroids, noon_dict,100, unfulfilled_rides=noon[['start_location_lat','start_location_long']])

[ 30.28435671  30.23832012  30.30856848  30.32807444  30.24189414]
[0.83, 0.51, 0.48, 0.47, 0.32]


This doesn't really seem like enough datapoints to justify placing drivers in any of these locations. Let's try including rides that were successful calls that led to a ride.
# Including successful ride requests

In [18]:
df_completed = pd.read_sql('SELECT start_location_lat,start_location_long, created_date FROM rides  WHERE status = "COMPLETED";', engine)

In [19]:
df_completed = df_completed[(df_completed['start_location_lat'] >= 30.190833) & (df_completed['start_location_lat'] <= 30.404041)]
df_completed = df_completed[(df_completed['start_location_long'] >=-97.819014) & (df_completed['start_location_long'] <= -97.647192)]
df_completed['day'] = df_completed['created_date'].dt.date
df_completed = df_completed[df_completed['day'] == dt.date(2016,10,9)]

In [20]:
comp_lats = list(df_completed['start_location_lat'])
comp_longs = list(df_completed['start_location_long'])
comp_noon = df_completed[(df_completed['created_date'] > dt.datetime(2016,10,9, 12,0,3)) & \
                   (df_completed['created_date'] < dt.datetime(2016,10,9, 15,0,3)) ]

In [21]:
X = np.concatenate((np.array(comp_noon[['start_location_lat','start_location_long']]),X), axis=0)
model = KMeans(n_clusters=5)
model.fit(X)
comp_centroids = model.cluster_centers_
comp_centroidlats = comp_centroids[:,0]
comp_centroidlongs = comp_centroids[:,1]

In [22]:
map_options = GMapOptions(lat=30.29, lng=-97.73, map_type="roadmap", zoom=11)

plot = GMapPlot(
    x_range=DataRange1d(), y_range=DataRange1d(), map_options=map_options
)
plot.title.text = "Austin"

# For GMaps to function, Google requires you obtain and enable an API key:
#
#     https://developers.google.com/maps/documentation/javascript/get-api-key
#
# Replace the value below with your personal API key:
plot.api_key = "AIzaSyBx-cLXm4jxpg0aX_nnUnwd2hir3Ve0j9w"

source = ColumnDataSource(
    data=dict(
        lat=noon_lats,
        lon=noon_longs,
    )
)
source2 = ColumnDataSource(
    data=dict(
        lat=comp_lats,
        lon=comp_longs,
    )
)
source1 = ColumnDataSource(
    data=dict(
        lat=comp_centroidlats,
        lon=comp_centroidlongs,
    )
)

circle = Circle(x="lon", y="lat", size=15, fill_color="blue", fill_alpha=0.8, line_color=None)
circle2 = Circle(x="lon", y="lat", size=15, fill_color="green", fill_alpha=0.1, line_color=None)
circle1 = Circle(x="lon", y="lat", size=45, fill_color="red", fill_alpha=0.7, line_color=None)
plot.add_glyph(source, circle)
plot.add_glyph(source2,circle2)
plot.add_glyph(source1,circle1)

plot.add_tools(PanTool(), WheelZoomTool(), BoxSelectTool())
show(plot)

# Averaging Unfulfilled Requests by Hour Block over a year

In [23]:
df_0_3 = pd.read_sql("SELECT start_location_lat,start_location_long FROM rides WHERE status = 'NO_AVAILABLE_DRIVER' AND tod  BETWEEN '00:00:00' AND '03:00:00' AND start_location_lat BETWEEN 30.190833 AND 30.404041 AND start_location_long BETWEEN -97.819014 AND -97.647192;",engine)
df_3_6 = pd.read_sql("SELECT start_location_lat,start_location_long FROM rides WHERE status = 'NO_AVAILABLE_DRIVER' AND tod  BETWEEN '03:00:00' AND '06:00:00' AND start_location_lat BETWEEN 30.190833 AND 30.404041 AND start_location_long BETWEEN -97.819014 AND -97.647192;",engine)
df_6_9 = pd.read_sql("SELECT start_location_lat,start_location_long FROM rides WHERE status = 'NO_AVAILABLE_DRIVER' AND tod  BETWEEN '06:00:00' AND '09:00:00' AND start_location_lat BETWEEN 30.190833 AND 30.404041 AND start_location_long BETWEEN -97.819014 AND -97.647192;",engine)

df_9_12 = pd.read_sql("SELECT start_location_lat,start_location_long FROM rides WHERE status = 'NO_AVAILABLE_DRIVER' AND tod  BETWEEN '09:00:00' AND '12:00:00' AND start_location_lat BETWEEN 30.190833 AND 30.404041 AND start_location_long BETWEEN -97.819014 AND -97.647192;",engine)

df_12_15 = pd.read_sql("SELECT start_location_lat,start_location_long FROM rides WHERE status = 'NO_AVAILABLE_DRIVER' AND tod  BETWEEN '12:00:00' AND '15:00:00' AND start_location_lat BETWEEN 30.190833 AND 30.404041 AND start_location_long BETWEEN -97.819014 AND -97.647192;",engine)

df_15_18 = pd.read_sql("SELECT start_location_lat,start_location_long FROM rides WHERE status = 'NO_AVAILABLE_DRIVER' AND tod  BETWEEN '15:00:00' AND '18:00:00' AND start_location_lat BETWEEN 30.190833 AND 30.404041 AND start_location_long BETWEEN -97.819014 AND -97.647192;",engine)

df_18_21 = pd.read_sql("SELECT start_location_lat,start_location_long FROM rides WHERE status = 'NO_AVAILABLE_DRIVER' AND tod  BETWEEN '18:00:00' AND '21:00:00' AND start_location_lat BETWEEN 30.190833 AND 30.404041 AND start_location_long BETWEEN -97.819014 AND -97.647192;",engine)

df_21_24 = pd.read_sql("SELECT start_location_lat,start_location_long FROM rides WHERE status = 'NO_AVAILABLE_DRIVER' AND tod  BETWEEN '21:00:00' AND '24:00:00' AND start_location_lat BETWEEN 30.190833 AND 30.404041 AND start_location_long BETWEEN -97.819014 AND -97.647192;",engine)


In [24]:
timelist = [df_0_3,df_3_6,df_6_9,df_9_12,df_12_15,df_15_18,df_18_21,df_21_24]
centroid_vectors = []

In [25]:
for dataframe in timelist:
    X = np.array(dataframe[['start_location_lat','start_location_long']])
    model = KMeans(n_clusters=5)
    model.fit(X)
    time_centroids = model.cluster_centers_
    centroid_vectors.append(time_centroids)

In [26]:
map_options = GMapOptions(lat=30.29, lng=-97.73, map_type="roadmap", zoom=11)

plot = GMapPlot(
    x_range=DataRange1d(), y_range=DataRange1d(), map_options=map_options, api_key = "AIzaSyBx-cLXm4jxpg0aX_nnUnwd2hir3Ve0j9w")
plot.title.text = "Austin"

# For GMaps to function, Google requires you obtain and enable an API key:
#
#     https://developers.google.com/maps/documentation/javascript/get-api-key
#
# Replace the value below with your personal API key:
sourcelist = []
circlelist = []
alpha = .19
colorlist = ['#084594', '#2171b5', '#4292c6', '#6baed6', '#9ecae1', '#c6dbef', '#deebf7', '#f7fbff']
for vector,color in zip(centroid_vectors,colorlist):
    centroidlats = vector[:,0]
    centroidlongs = vector[:,1]
    source1 = ColumnDataSource(
        data=dict(
            lat=centroidlats,
            lon=centroidlongs,
        )
    )
    sourcelist.append(source1)
    circle1 = Circle(x="lon", y="lat", size=45, fill_color=color, fill_alpha=.9, line_color=None)
    alpha += .1 
    circlelist.append(circle1)



In [27]:
len(sourcelist)

8

In [28]:

plot.add_glyph(sourcelist[0], circlelist[0])
plot.add_glyph(sourcelist[1],circlelist[1])
plot.add_glyph(sourcelist[2],circlelist[2])
plot.add_glyph(sourcelist[3],circlelist[3])
plot.add_glyph(sourcelist[4],circlelist[4])
plot.add_glyph(sourcelist[5],circlelist[5])
plot.add_glyph(sourcelist[6],circlelist[6])
plot.add_glyph(sourcelist[7],circlelist[7])
plot.add_tools(PanTool(), WheelZoomTool(), BoxSelectTool())
show(plot)

# Average by half hour time-block

In [29]:
df_before = pd.read_sql("SELECT start_location_lat, start_location_long, status FROM rides WHERE created_date BETWEEN '2016-10-09 12:00:00' AND '2016-10-09 12:30:00' AND start_location_lat BETWEEN 30.190833 AND 30.404041 AND start_location_long BETWEEN -97.819014 AND -97.647192 HAVING status = 'completed' OR status= 'no_available_driver';",engine)
df_after = pd.read_sql("SELECT start_location_lat, start_location_long, status FROM rides WHERE created_date BETWEEN '2016-10-09 12:30:00' AND '2016-10-09 13:00:00' AND start_location_lat BETWEEN 30.190833 AND 30.404041 AND start_location_long BETWEEN -97.819014 AND -97.647192 HAVING status = 'completed' OR status= 'no_available_driver';",engine)


In [30]:
#sanity check
print len(df_before)
print len(df_after)
df_before.head()

80
36


start_location_lat  start_location_long               status
0           30.394403           -97.726407            COMPLETED
1           30.268982           -97.740335            COMPLETED
2           30.315679           -97.724534            COMPLETED
3           30.251609           -97.761293  NO_AVAILABLE_DRIVER
4           30.271964           -97.754260  NO_AVAILABLE_DRIVER

In [31]:
before_centroids, before_dict = create_centroids(df_before)
plot_Austin_centroids(before_centroids, before_dict, len(df_before), unfulfilled_rides=df_before)

[[ 30.26851982 -97.74630767]
 [ 30.29259797 -97.7424486 ]
 [ 30.24695795 -97.77228286]
 [ 30.22533313 -97.71624835]
 [ 30.37203067 -97.721613  ]]
{0: [30.268519815627243, -97.746307674711275, 26, 0], 1: [30.292597966723811, -97.742448600314518, 24, 1], 2: [30.246957954545454, -97.772282863636363, 22, 2], 3: [30.225333127466129, -97.716248346597482, 5, 3], 4: [30.372030666666667, -97.721612999999991, 3, 4]}
[ 30.26851982  30.29259797  30.24695795  30.22533313  30.37203067]
[0.575, 0.55, 0.525, 0.3125, 0.2875]


In [32]:
after_centroids, after_dict = create_centroids(df_after)
plot_Austin_centroids(after_centroids, after_dict, len(df_after))

[[ 30.27948307 -97.75185019]
 [ 30.26555113 -97.71424838]
 [ 30.23474677 -97.76990003]
 [ 30.353997   -97.76566567]
 [ 30.36292615 -97.6914741 ]]
{0: [30.279483068661275, -97.751850194859401, 15, 0], 1: [30.265551133236237, -97.714248382464589, 8, 1], 2: [30.234746768054084, -97.769900029207889, 8, 2], 3: [30.353997, -97.765665666666663, 3, 3], 4: [30.362926149999996, -97.691474099999994, 2, 4]}
[ 30.27948307  30.26555113  30.23474677  30.353997    30.36292615]
[0.6666666666666667, 0.4722222222222222, 0.4722222222222222, 0.3333333333333333, 0.3055555555555556]


Follow up from Friday:
Look at alice and wonderland example
Filter data into lat,long,timbeblock,day of week
isolate pair of data at noon on birthday. 
generate distance metric
find pairs similar to that pair via distance metric
populate a distribution with the points that follow that metric
randomly pull from that distribution
lather rinse repeat.